# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         OMA-Download-DRM
version:      1.00.04
version_from: lib/OMA/Download/DRM.pm
installdirs:  site
requires:
    Crypt::Rijndael:               0.04

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
